---
- name: configure ELK vm with docker
  hosts: elk
  become: true
  tasks:
  - name: increase memory
    command: sysctl -w vm.max_map_count=262144
  - name: docker.io
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present
  - name: install pip
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present
  - name: install python docker
    pip:
      name: docker
      state: present
  - name: download docker container
    docker_container:
      name: elk
      image: sebp/elk:761
      state: started
      restart_policy: always
      published_ports:
        - 5601:5601
        - 9200:9200
        - 5044:5044
  - name: enable docker service
    systemd:
      name: docker
      enabled: yes